CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    email VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS items(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner_id BIGINT,
    name VARCHAR(100),
    description VARCHAR,
    available BOOLEAN,
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);